services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: "pip install -r frontend/requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: FASTAPI_URL
        value: "https://fastapi-backend.onrender.com"  # Replace with your actual backend URL after deploy
      - key: PYTHON_VERSION
        value: 3.10
